-- Seed local de App de Compras.
--
-- Intencionalmente vacío: todas las tablas de dominio (families, products, shopping_lists…)
-- cuelgan de un usuario de auth.users, que se crea al registrarse desde la app.
-- El primer ingreso crea "Mi Familia" automáticamente (ShoppingListFacade.getOrCreateFamily).
